name: CI/CD for Azure Container Apps

on:
  push:
    branches:
      - main  # Adjust the branch name as per your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Azure Login
        run: az login
      - name: Azure CLI script
        uses: azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Build and push Docker image to ACR
        run: |
          docker login cr0123.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker build . -t cr0123.azurecr.io/hello-world-node:latest 
          docker push cr0123.azurecr.io/hello-world-node:latest

      - name: Deploy to Azure Container Apps
        run: |
          RESOURCE_GROUP=rg
          CONTAINER_APP_NAME=hello
          ACR_LOGIN_SERVER=cr0123.azurecr.io
          IMAGE_NAME=hello-world-node:latest
          ENVIRONMENT_NAME=managedEnvironment-rg-95d1
          
          CONTAINER_APP_EXISTS=$(az containerapp show --name $CONTAINER_APP_NAME --resource-group $RESOURCE_GROUP --query "name" --output tsv || echo "none")
        
         
          if [ "$CONTAINER_APP_EXISTS" = "none" ]; then 
          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_LOGIN_SERVER/$IMAGE_NAME \
            --environment $ENVIRONMENT_NAME \
            --registry-server $ACR_LOGIN_SERVER \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }}

             else
            az containerapp update \
              --name $CONTAINER_APP_NAME \
              --resource-group $RESOURCE_GROUP \
              --image $ACR_LOGIN_SERVER/$IMAGE_NAME \
              --registry-login-server $ACR_LOGIN_SERVER \
              --registry-username ${{ secrets.ACR_USERNAME }} \
              --registry-password ${{ secrets.ACR_PASSWORD }}
          fi

      - name: Azure Logout
        run: az logout
