name: CI/CD for Azure Container Apps

on:
  push:
    branches:
      - main  # Adjust the branch name as per your main branch
      
permissions:
       id-token: write
       contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push Docker image to ACR
        run: |
          docker login cr0123.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker build . -t cr0123.azurecr.io/hello-world-node:latest 
          docker push cr0123.azurecr.io/hello-world-node:latest

      - name: Deploy to Azure Container Apps
        run: |
          RESOURCE_GROUP=rg
          CONTAINER_APP_NAME=hello
          ACR_LOGIN_SERVER=cr0123.azurecr.io
          IMAGE_NAME=hello-world-node:latest
          ENVIRONMENT_NAME=managedEnvironment-rg-95d1
          

