name: CI/CD for Azure Container Apps

on:
  push:
    branches:
      - main  # Adjust the branch name as per your main branch

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: cr0123.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image to ACR
        run: |
          docker build . -t cr0123.azurecr.io/hello:${{ github.sha }}
          docker push cr0123.azurecr.io/hello:${{ github.sha }}

      - name: Deploy to Azure Container Apps
        run: |
          RESOURCE_GROUP=rg
          CONTAINER_APP_NAME=hello
          ACR_LOGIN_SERVER=cr0123.azurecr.io
          IMAGE_NAME=cr0123.azurecr.io/hello

          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}

