name: CI/CD for Azure Container Apps

on:
  push:
    branches:
      - main  # Adjust the branch name as per your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: cr0123.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Azure PowerShell script
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
            Get-AzContext

      - name: Build and push Docker image to ACR
        run: |
          docker build -t cr0123.azurecr.io/hello-world-node:latest .
          docker push cr0123.azurecr.io/hello-world-node:latest

      - name: Deploy to Azure Container Apps
        uses: azure/webapps-deploy@v2
        with:
          app-name: hello
          images: 'cr0123.azurecr.io/hello-world-node:latest'

